version: '3.9'

services:
  backend:
    build:
      context: backend
      dockerfile: backend.Dockerfile
    image: backend
    container_name: backend
    ports:
    - "8080:8080"
    env_file:
      - backend/.env
    networks:
      - service_network

  frontend:
    build:
      context: frontend
      dockerfile: frontend.Dockerfile
    image: frontend
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env
    networks:
      - service_network

networks:
  service_network:
