version: '3.9'

services:
  fs:
    image: postgres
    container_name: fs
    restart: always
    env_file:
      - ".env"
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"